import Link from "next/link";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <nav>
          <li>
            <Link href="/">Home</Link>
          </li>
          <li>
            <Link href="/product">Product</Link>
          </li>
          <li>
            <Link href="/product/100">Product-Loading</Link>
          </li>
          <li>
            <Link href="/book">Book</Link>
          </li>
          <li>
            <Link href="/dashboard">Dashboard</Link>
          </li>
        </nav>
        {children}
      </body>
    </html>
  );
}
