
export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function BookLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <h5>Book Data </h5>
        {children}
      </body>
    </html>
  );
}
